#!/usr/bin/env bash
# A Bash scripts that pings an IP address passed as an argument:
# It accepts a string as an arg
# It displays usage: 5-is_the_host_on_the_network {IP_ADDRESS}
#if no argument is passed
# Ping the IP 5 times

if [ $# -eq 0 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
elif [ $# -gt 1 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
else
	ping "$1" -c 5
fi
