#!/usr/bin/env bash
# Script that displays numbers from 1 to 100
# Display "Fizzbuzz" when number is mutiple of 3 and 5
# Displays "Buzz" when number is a multiple of 5
# Displays "Fizz" when number is a multiple of 3
# Displays the number otherwise.

for x in {1..100}
do
	if (( x % 3 ==0 && x % 5 == 0))
	then
		echo "FizzBuzz"
	elif (( x % 3 == 0 ))
	then
		echo "Fizz"
	elif (( x % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$x"
	fi
done
