#!/usr/bin/env bash
#To display "Best School" 9 times followed by "hi"
i=1
while [ "$1" -le 10 ]
do
	if [ "$i" -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	i=$(( i + 1 ))
done
