#!/usr/bin/env bash
# To display contents of the current directory in list format
# To display only the part of the name after the first dash.

list=$(ls)
for i in $list;
do
	echo "$i" | cut -d '-' -f2
done
