#!/usr/bin/env bash
#A bash script that configures an ubuntu server with below requirements:
# Local host to 127.0.0.2
# facebook.com resolves to 8.8.8.8
# Checker runs on Docker

cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts 
